Test unitaire sur la route /predict
JoffreyLGT/e-commerce-mlops pull request #48
Opened 2023-08-03 08:33 UTC by Landry-G01

-test sur les valeurs correctes ( bonne extension, format limit )
-test sur les valeurs incorrectes (  mauvaise limit, format, extension)
-test sur les valeurs manquantes ( aucune donnée saisie ou entrée)

2023-08-03 08:38 UTC, GuetchArnaud approved these changes
Ok for these changes.

2023-08-03 08:51 UTC, JoffreyLGT commented
Ne pas merge pour le moment.

2023-08-03 09:11 UTC, JoffreyLGT commented
Part of #41

2023-08-03 09:49 UTC, JoffreyLGT requested changes

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +# client = TestClient(app)
Code mort, à retirer.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +def test_predict_category_with_valid_data(
Le nom de la fonction indique valid_data, mais la docstring parle de mauvaise information.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    designation = "designation"
Mettre des données vraisemblable pour pouvoir anticiper la réponse du model.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    image = Image.new("RGB", (100, 100))  # test image uploaded in color
Tester le scenario ou l'utilisateur envoi une image en noir et blanc.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +        params={"designation": designation, "description": description, "limit": limit},
Faire toute la déclaration de l'objet au même endroit.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    limit_negative = -1
Chaque cas d'utilisation doit être mis dans son propre test unitaire. L'objectif est d'avoir une liste des cas d'utilisation et d'identifier le cas problématiques.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +
Vérifier la réponse pour s'assurer qu'elle renvoi ce qu'on attendait.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    request = client.post(
Il manque l'authentification.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    """test of the prediction with wrong image format;
Format docstring incorrecte.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    """Test  the prediction with empty data
Format docstring incorrecte.

2023-08-03 09:49 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +def test_predict_category_without_data(client: TestClient):
L'objectif est-il de tester si l'accès est public ou privé ?
Ou est-ce qu'on veux juste vérifier que des données ont été envoyées ?

2023-08-05 13:31 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    image = Image.new(
Pour information, ceci n'est pas une image en noir et blanc vu qu'elle est toujours sur 3 canaux.

2023-08-05 13:52 UTC, JoffreyLGT commented on backend/app/tests/api/endpoints/test_prediction.py
> +    image = Image.new(
https://pillow.readthedocs.io/en/stable/handbook/concepts.html

2023-08-05 13:52 UTC, JoffreyLGT submitted a review, later dismissed

2023-08-05 13:54 UTC, JoffreyLGT approved these changes

2023-08-05 13:56 UTC, JoffreyLGT approved these changes

2023-08-05 13:56 UTC, JoffreyLGT approved these changes

2023-08-06 07:32 UTC, GuetchArnaud approved these changes
Approv and submit my review.

2023-08-06 07:59 UTC, merged